package com.bugtool.model;


/**
 * BugInfo generated by rsunkari
 */
public class BugInfo implements java.io.Serializable {

	private Integer id;
	private String steps;
	private String developerEffort;
	private String description;
	private String rootcause;
	private String solution;
	private String workaround;
	private String technicalLearning;
	private String domainLearning;
	private String status;
	private String envInfo;
	private Integer userId;
	private byte[] supportFile;

	public byte[] getSupportFile() {
		return supportFile;
	}

	public void setSupportFile(byte[] supportFile) {
		this.supportFile = supportFile;
	}

	public BugInfo() {
	}


	public BugInfo(Integer id, String steps, String developerEffort,
			String description, String rootcause, String solution,
			String workaround, String technicalLearning, String domainLearning,
			String status, String envInfo, Integer userId, byte[] supportFile) {
		this.id = id;
		this.steps = steps;
		this.developerEffort = developerEffort;
		this.description = description;
		this.rootcause = rootcause;
		this.solution = solution;
		this.workaround = workaround;
		this.technicalLearning = technicalLearning;
		this.domainLearning = domainLearning;
		this.status = status;
		this.envInfo = envInfo;
		this.userId = userId;
		this.supportFile = supportFile;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSteps() {
		return this.steps;
	}

	public void setSteps(String steps) {
		this.steps = steps;
	}

	public String getDeveloperEffort() {
		return this.developerEffort;
	}

	public void setDeveloperEffort(String developerEffort) {
		this.developerEffort = developerEffort;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRootcause() {
		return this.rootcause;
	}

	public void setRootcause(String rootcause) {
		this.rootcause = rootcause;
	}

	public String getSolution() {
		return this.solution;
	}

	public void setSolution(String solution) {
		this.solution = solution;
	}

	public String getWorkaround() {
		return this.workaround;
	}

	public void setWorkaround(String workaround) {
		this.workaround = workaround;
	}

	public String getTechnicalLearning() {
		return this.technicalLearning;
	}

	public void setTechnicalLearning(String technicalLearning) {
		this.technicalLearning = technicalLearning;
	}

	public String getDomainLearning() {
		return this.domainLearning;
	}

	public void setDomainLearning(String domainLearning) {
		this.domainLearning = domainLearning;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getEnvInfo() {
		return this.envInfo;
	}

	public void setEnvInfo(String envInfo) {
		this.envInfo = envInfo;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BugInfo other = (BugInfo) obj;
		if (description == null) {
			if (other.description != null)
				return false;
		} else if (!description.equals(other.description))
			return false;
		if (developerEffort == null) {
			if (other.developerEffort != null)
				return false;
		} else if (!developerEffort.equals(other.developerEffort))
			return false;
		if (domainLearning == null) {
			if (other.domainLearning != null)
				return false;
		} else if (!domainLearning.equals(other.domainLearning))
			return false;
		if (envInfo == null) {
			if (other.envInfo != null)
				return false;
		} else if (!envInfo.equals(other.envInfo))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (rootcause == null) {
			if (other.rootcause != null)
				return false;
		} else if (!rootcause.equals(other.rootcause))
			return false;
		if (solution == null) {
			if (other.solution != null)
				return false;
		} else if (!solution.equals(other.solution))
			return false;
		if (status == null) {
			if (other.status != null)
				return false;
		} else if (!status.equals(other.status))
			return false;
		if (steps == null) {
			if (other.steps != null)
				return false;
		} else if (!steps.equals(other.steps))
			return false;
		if (technicalLearning == null) {
			if (other.technicalLearning != null)
				return false;
		} else if (!technicalLearning.equals(other.technicalLearning))
			return false;
		if (userId == null) {
			if (other.userId != null)
				return false;
		} else if (!userId.equals(other.userId))
			return false;
		if (workaround == null) {
			if (other.workaround != null)
				return false;
		} else if (!workaround.equals(other.workaround))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((description == null) ? 0 : description.hashCode());
		result = prime * result
				+ ((developerEffort == null) ? 0 : developerEffort.hashCode());
		result = prime * result
				+ ((domainLearning == null) ? 0 : domainLearning.hashCode());
		result = prime * result + ((envInfo == null) ? 0 : envInfo.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((rootcause == null) ? 0 : rootcause.hashCode());
		result = prime * result
				+ ((solution == null) ? 0 : solution.hashCode());
		result = prime * result + ((status == null) ? 0 : status.hashCode());
		result = prime * result + ((steps == null) ? 0 : steps.hashCode());
		result = prime
				* result
				+ ((technicalLearning == null) ? 0 : technicalLearning
						.hashCode());
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		result = prime * result
				+ ((workaround == null) ? 0 : workaround.hashCode());
		return result;
	}
}
