//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.02 at 06:25:14 PM EST 
//


package com.thinkadv.springmvc.pivotol.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.thinkadv.springmvc.pivotol.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.thinkadv.springmvc.pivotol.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Projects }
     * 
     */
    public Projects createProjects() {
        return new Projects();
    }

    /**
     * Create an instance of {@link Projects.Project }
     * 
     */
    public Projects.Project createProjectsProject() {
        return new Projects.Project();
    }

    /**
     * Create an instance of {@link Projects.Project.Memberships }
     * 
     */
    public Projects.Project.Memberships createProjectsProjectMemberships() {
        return new Projects.Project.Memberships();
    }

    /**
     * Create an instance of {@link Projects.Project.Memberships.Membership }
     * 
     */
    public Projects.Project.Memberships.Membership createProjectsProjectMembershipsMembership() {
        return new Projects.Project.Memberships.Membership();
    }

    /**
     * Create an instance of {@link Projects.Project.IterationLength }
     * 
     */
    public Projects.Project.IterationLength createProjectsProjectIterationLength() {
        return new Projects.Project.IterationLength();
    }

    /**
     * Create an instance of {@link Projects.Project.StartDate }
     * 
     */
    public Projects.Project.StartDate createProjectsProjectStartDate() {
        return new Projects.Project.StartDate();
    }

    /**
     * Create an instance of {@link Projects.Project.FirstIterationStartTime }
     * 
     */
    public Projects.Project.FirstIterationStartTime createProjectsProjectFirstIterationStartTime() {
        return new Projects.Project.FirstIterationStartTime();
    }

    /**
     * Create an instance of {@link Projects.Project.CurrentIterationNumber }
     * 
     */
    public Projects.Project.CurrentIterationNumber createProjectsProjectCurrentIterationNumber() {
        return new Projects.Project.CurrentIterationNumber();
    }

    /**
     * Create an instance of {@link Projects.Project.EnableTasks }
     * 
     */
    public Projects.Project.EnableTasks createProjectsProjectEnableTasks() {
        return new Projects.Project.EnableTasks();
    }

    /**
     * Create an instance of {@link Projects.Project.LastActivityAt }
     * 
     */
    public Projects.Project.LastActivityAt createProjectsProjectLastActivityAt() {
        return new Projects.Project.LastActivityAt();
    }

    /**
     * Create an instance of {@link Projects.Project.Integrations }
     * 
     */
    public Projects.Project.Integrations createProjectsProjectIntegrations() {
        return new Projects.Project.Integrations();
    }

    /**
     * Create an instance of {@link Projects.Project.Memberships.Membership.Person }
     * 
     */
    public Projects.Project.Memberships.Membership.Person createProjectsProjectMembershipsMembershipPerson() {
        return new Projects.Project.Memberships.Membership.Person();
    }

}
