//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.02 at 06:25:14 PM EST 
//


package com.thinkadv.springmvc.pivotol.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="project">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="iteration_length">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="week_start_day" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="point_scale" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="account" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="start_date">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="first_iteration_start_time">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="current_iteration_number">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="enable_tasks">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="velocity_scheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="current_velocity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="initial_velocity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="number_of_done_iterations_to_show" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="labels" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="last_activity_at">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="allow_attachments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="public" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="use_https" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="bugs_and_chores_are_estimatable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="commit_mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="memberships">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="membership" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="person">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="initials" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="integrations">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "project"
})
@XmlRootElement(name = "projects")
public class Projects {

    @XmlElement(required = true)
    protected Projects.Project project;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link Projects.Project }
     *     
     */
    public Projects.Project getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link Projects.Project }
     *     
     */
    public void setProject(Projects.Project value) {
        this.project = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="iteration_length">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="week_start_day" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="point_scale" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="account" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="start_date">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="first_iteration_start_time">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="current_iteration_number">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="enable_tasks">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="velocity_scheme" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="current_velocity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="initial_velocity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="number_of_done_iterations_to_show" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="labels" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="last_activity_at">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="allow_attachments" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="public" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="use_https" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="bugs_and_chores_are_estimatable" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="commit_mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="memberships">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="membership" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="person">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="initials" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="integrations">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name",
        "iterationLength",
        "weekStartDay",
        "pointScale",
        "account",
        "startDate",
        "firstIterationStartTime",
        "currentIterationNumber",
        "enableTasks",
        "velocityScheme",
        "currentVelocity",
        "initialVelocity",
        "numberOfDoneIterationsToShow",
        "labels",
        "lastActivityAt",
        "allowAttachments",
        "_public",
        "useHttps",
        "bugsAndChoresAreEstimatable",
        "commitMode",
        "memberships",
        "integrations"
    })
    public static class Project {

        protected int id;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(name = "iteration_length", required = true)
        protected Projects.Project.IterationLength iterationLength;
        @XmlElement(name = "week_start_day", required = true)
        protected String weekStartDay;
        @XmlElement(name = "point_scale", required = true)
        protected String pointScale;
        @XmlElement(required = true)
        protected String account;
        @XmlElement(name = "start_date", required = true)
        protected Projects.Project.StartDate startDate;
        @XmlElement(name = "first_iteration_start_time", required = true)
        protected Projects.Project.FirstIterationStartTime firstIterationStartTime;
        @XmlElement(name = "current_iteration_number", required = true)
        protected Projects.Project.CurrentIterationNumber currentIterationNumber;
        @XmlElement(name = "enable_tasks", required = true)
        protected Projects.Project.EnableTasks enableTasks;
        @XmlElement(name = "velocity_scheme", required = true)
        protected String velocityScheme;
        @XmlElement(name = "current_velocity")
        protected byte currentVelocity;
        @XmlElement(name = "initial_velocity")
        protected byte initialVelocity;
        @XmlElement(name = "number_of_done_iterations_to_show")
        protected byte numberOfDoneIterationsToShow;
        @XmlElement(required = true)
        protected String labels;
        @XmlElement(name = "last_activity_at", required = true)
        protected Projects.Project.LastActivityAt lastActivityAt;
        @XmlElement(name = "allow_attachments", required = true)
        protected String allowAttachments;
        @XmlElement(name = "public", required = true)
        protected String _public;
        @XmlElement(name = "use_https", required = true)
        protected String useHttps;
        @XmlElement(name = "bugs_and_chores_are_estimatable", required = true)
        protected String bugsAndChoresAreEstimatable;
        @XmlElement(name = "commit_mode", required = true)
        protected String commitMode;
        @XmlElement(required = true)
        protected Projects.Project.Memberships memberships;
        @XmlElement(required = true)
        protected Projects.Project.Integrations integrations;

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the iterationLength property.
         * 
         * @return
         *     possible object is
         *     {@link Projects.Project.IterationLength }
         *     
         */
        public Projects.Project.IterationLength getIterationLength() {
            return iterationLength;
        }

        /**
         * Sets the value of the iterationLength property.
         * 
         * @param value
         *     allowed object is
         *     {@link Projects.Project.IterationLength }
         *     
         */
        public void setIterationLength(Projects.Project.IterationLength value) {
            this.iterationLength = value;
        }

        /**
         * Gets the value of the weekStartDay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWeekStartDay() {
            return weekStartDay;
        }

        /**
         * Sets the value of the weekStartDay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWeekStartDay(String value) {
            this.weekStartDay = value;
        }

        /**
         * Gets the value of the pointScale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPointScale() {
            return pointScale;
        }

        /**
         * Sets the value of the pointScale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPointScale(String value) {
            this.pointScale = value;
        }

        /**
         * Gets the value of the account property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccount() {
            return account;
        }

        /**
         * Sets the value of the account property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccount(String value) {
            this.account = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link Projects.Project.StartDate }
         *     
         */
        public Projects.Project.StartDate getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Projects.Project.StartDate }
         *     
         */
        public void setStartDate(Projects.Project.StartDate value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the firstIterationStartTime property.
         * 
         * @return
         *     possible object is
         *     {@link Projects.Project.FirstIterationStartTime }
         *     
         */
        public Projects.Project.FirstIterationStartTime getFirstIterationStartTime() {
            return firstIterationStartTime;
        }

        /**
         * Sets the value of the firstIterationStartTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Projects.Project.FirstIterationStartTime }
         *     
         */
        public void setFirstIterationStartTime(Projects.Project.FirstIterationStartTime value) {
            this.firstIterationStartTime = value;
        }

        /**
         * Gets the value of the currentIterationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Projects.Project.CurrentIterationNumber }
         *     
         */
        public Projects.Project.CurrentIterationNumber getCurrentIterationNumber() {
            return currentIterationNumber;
        }

        /**
         * Sets the value of the currentIterationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Projects.Project.CurrentIterationNumber }
         *     
         */
        public void setCurrentIterationNumber(Projects.Project.CurrentIterationNumber value) {
            this.currentIterationNumber = value;
        }

        /**
         * Gets the value of the enableTasks property.
         * 
         * @return
         *     possible object is
         *     {@link Projects.Project.EnableTasks }
         *     
         */
        public Projects.Project.EnableTasks getEnableTasks() {
            return enableTasks;
        }

        /**
         * Sets the value of the enableTasks property.
         * 
         * @param value
         *     allowed object is
         *     {@link Projects.Project.EnableTasks }
         *     
         */
        public void setEnableTasks(Projects.Project.EnableTasks value) {
            this.enableTasks = value;
        }

        /**
         * Gets the value of the velocityScheme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVelocityScheme() {
            return velocityScheme;
        }

        /**
         * Sets the value of the velocityScheme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVelocityScheme(String value) {
            this.velocityScheme = value;
        }

        /**
         * Gets the value of the currentVelocity property.
         * 
         */
        public byte getCurrentVelocity() {
            return currentVelocity;
        }

        /**
         * Sets the value of the currentVelocity property.
         * 
         */
        public void setCurrentVelocity(byte value) {
            this.currentVelocity = value;
        }

        /**
         * Gets the value of the initialVelocity property.
         * 
         */
        public byte getInitialVelocity() {
            return initialVelocity;
        }

        /**
         * Sets the value of the initialVelocity property.
         * 
         */
        public void setInitialVelocity(byte value) {
            this.initialVelocity = value;
        }

        /**
         * Gets the value of the numberOfDoneIterationsToShow property.
         * 
         */
        public byte getNumberOfDoneIterationsToShow() {
            return numberOfDoneIterationsToShow;
        }

        /**
         * Sets the value of the numberOfDoneIterationsToShow property.
         * 
         */
        public void setNumberOfDoneIterationsToShow(byte value) {
            this.numberOfDoneIterationsToShow = value;
        }

        /**
         * Gets the value of the labels property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabels() {
            return labels;
        }

        /**
         * Sets the value of the labels property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabels(String value) {
            this.labels = value;
        }

        /**
         * Gets the value of the lastActivityAt property.
         * 
         * @return
         *     possible object is
         *     {@link Projects.Project.LastActivityAt }
         *     
         */
        public Projects.Project.LastActivityAt getLastActivityAt() {
            return lastActivityAt;
        }

        /**
         * Sets the value of the lastActivityAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Projects.Project.LastActivityAt }
         *     
         */
        public void setLastActivityAt(Projects.Project.LastActivityAt value) {
            this.lastActivityAt = value;
        }

        /**
         * Gets the value of the allowAttachments property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllowAttachments() {
            return allowAttachments;
        }

        /**
         * Sets the value of the allowAttachments property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllowAttachments(String value) {
            this.allowAttachments = value;
        }

        /**
         * Gets the value of the public property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPublic() {
            return _public;
        }

        /**
         * Sets the value of the public property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPublic(String value) {
            this._public = value;
        }

        /**
         * Gets the value of the useHttps property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUseHttps() {
            return useHttps;
        }

        /**
         * Sets the value of the useHttps property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUseHttps(String value) {
            this.useHttps = value;
        }

        /**
         * Gets the value of the bugsAndChoresAreEstimatable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBugsAndChoresAreEstimatable() {
            return bugsAndChoresAreEstimatable;
        }

        /**
         * Sets the value of the bugsAndChoresAreEstimatable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBugsAndChoresAreEstimatable(String value) {
            this.bugsAndChoresAreEstimatable = value;
        }

        /**
         * Gets the value of the commitMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCommitMode() {
            return commitMode;
        }

        /**
         * Sets the value of the commitMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCommitMode(String value) {
            this.commitMode = value;
        }

        /**
         * Gets the value of the memberships property.
         * 
         * @return
         *     possible object is
         *     {@link Projects.Project.Memberships }
         *     
         */
        public Projects.Project.Memberships getMemberships() {
            return memberships;
        }

        /**
         * Sets the value of the memberships property.
         * 
         * @param value
         *     allowed object is
         *     {@link Projects.Project.Memberships }
         *     
         */
        public void setMemberships(Projects.Project.Memberships value) {
            this.memberships = value;
        }

        /**
         * Gets the value of the integrations property.
         * 
         * @return
         *     possible object is
         *     {@link Projects.Project.Integrations }
         *     
         */
        public Projects.Project.Integrations getIntegrations() {
            return integrations;
        }

        /**
         * Sets the value of the integrations property.
         * 
         * @param value
         *     allowed object is
         *     {@link Projects.Project.Integrations }
         *     
         */
        public void setIntegrations(Projects.Project.Integrations value) {
            this.integrations = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class CurrentIterationNumber {

            @XmlValue
            protected byte value;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             */
            public byte getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(byte value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class EnableTasks {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class FirstIterationStartTime {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Integrations {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class IterationLength {

            @XmlValue
            protected byte value;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             */
            public byte getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(byte value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class LastActivityAt {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="membership" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="person">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="initials" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "membership"
        })
        public static class Memberships {

            protected List<Projects.Project.Memberships.Membership> membership;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the membership property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the membership property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getMembership().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Projects.Project.Memberships.Membership }
             * 
             * 
             */
            public List<Projects.Project.Memberships.Membership> getMembership() {
                if (membership == null) {
                    membership = new ArrayList<Projects.Project.Memberships.Membership>();
                }
                return this.membership;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="person">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="initials" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "person",
                "role"
            })
            public static class Membership {

                protected int id;
                @XmlElement(required = true)
                protected Projects.Project.Memberships.Membership.Person person;
                @XmlElement(required = true)
                protected String role;

                /**
                 * Gets the value of the id property.
                 * 
                 */
                public int getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 */
                public void setId(int value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the person property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Projects.Project.Memberships.Membership.Person }
                 *     
                 */
                public Projects.Project.Memberships.Membership.Person getPerson() {
                    return person;
                }

                /**
                 * Sets the value of the person property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Projects.Project.Memberships.Membership.Person }
                 *     
                 */
                public void setPerson(Projects.Project.Memberships.Membership.Person value) {
                    this.person = value;
                }

                /**
                 * Gets the value of the role property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRole() {
                    return role;
                }

                /**
                 * Sets the value of the role property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRole(String value) {
                    this.role = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="initials" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "email",
                    "name",
                    "initials"
                })
                public static class Person {

                    @XmlElement(required = true)
                    protected String email;
                    @XmlElement(required = true)
                    protected String name;
                    @XmlElement(required = true)
                    protected String initials;

                    /**
                     * Gets the value of the email property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getEmail() {
                        return email;
                    }

                    /**
                     * Sets the value of the email property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setEmail(String value) {
                        this.email = value;
                    }

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the initials property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getInitials() {
                        return initials;
                    }

                    /**
                     * Sets the value of the initials property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setInitials(String value) {
                        this.initials = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class StartDate {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }

}
